version: '2'
services:
  lb:
    restart: always
    image: 'dockercloud/haproxy:latest'
    networks:
      - front
      - prosody
    links:
      - web
      - prosody
    ports:
      #HTTPS
      - '443:443'

      #Prosody
      - 5222:5222 #c2s port
      - 5269:5269 #s2s port
      - 5347:5347 #XMPP component port
      - 5280:5280 #BOSH / websocket port
      - 5281:5281 #Secure BOSH / websocket port
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - certs:/certs/
    environment:
      CERT_FOLDER: /certs/

  web:
    restart: always
    build: web/
    networks:
      - front
      - db
      - prosody
    volumes:
      - data:/var/www/html/claroline
      - certs:/certs/
    environment:
      VIRTUAL_HOST: https://claroline.loc, http://claroline.loc
      FORCE_SSL: "yes"
      APP_URL: claroline.loc
      DB_HOST: db
      DB_NAME: claroline
      DB_USER: claroline
      DB_PASSWORD: claroline
      SECRET: change_me

  db:
    restart: always
    image: mysql
    networks:
      - db
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: claroline
      MYSQL_PASSWORD: claroline
      MYSQL_DATABASE: claroline

  prosody:
    restart: always
    image: prosody/prosody
    volumes:
      - ./prosody/config:/etc/prosody
      - prosody:/var/lib/prosody
    environment:
      VIRTUAL_HOST: http://xmpp.claroline.loc
      TCP_PORTS: "5222, 5269, 5347, 5280, 5281"
      LOCAL: admin
      PASSWORD: admin
      DOMAIN: claroline.loc
    networks:
      - prosody

    #Exposed for debug
    #ports:
      #- 5222:5222 #c2s port
      #- 5269:5269 #s2s port
      #- 5347:5347 #XMPP component port
      #- 5280:5280 #BOSH / websocket port
      #- 5281:5281 #Secure BOSH / websocket port

networks:
  front:
  db:
  prosody:

volumes:
  data:
  mysql:
  certs:
  prosody:
